[versions]
java = "25"
kotlin_version = { strictly = "2.3.10" }
compose_multiplatform_vsersion = { strictly = "1.10.1" }
lifecycle = { strictly = "2.8.0" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin_version" }

compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose_multiplatform_vsersion" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin_version" }

spotless = { id = "com.diffplug.spotless", version = { strictly = "8.2.1" } }

[libraries]
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = { strictly = "0.7.1-0.6.x-compat" } }

compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose_multiplatform_vsersion" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose_multiplatform_vsersion" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version = { strictly = "1.10.0-alpha05" } }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose_multiplatform_vsersion" }
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose_multiplatform_vsersion" }
compose-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose_multiplatform_vsersion" }
components-ui-tooling-preview = { module = "org.jetbrains.compose.components:components-ui-tooling-preview", version.ref = "compose_multiplatform_vsersion" }
compose-adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive", version = { strictly = "1.3.0-alpha04" } }
material-icons-extended = { module = "org.jetbrains.compose.material:material-icons-extended", version = { strictly = "1.7.3" } }
material3-adaptive-navigation-suite = { module = "org.jetbrains.compose.material3:material3-adaptive-navigation-suite", version = { strictly = "1.11.0-alpha02" } }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
